name: Generate Changelog JSON

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  PR_NUMBER: ${{ github.event.number }}
  CHANGE_TITLE: ${{ github.event.pull_request.title }}
  CHANGE_SUMMARY: $(echo "${{ github.event.pull_request.body }}" | head -n 100)
  SEMANTIC_VERSION_TYPE: patch
  BUILD_RUNTIME_LABEL: require-runtime-build
  APP_STORE_REVIEW_LABEL: require-app-store-review
  USER_FACING_MAJOR: user-facing-major
  USER_FACING_MINOR: user-facing-minor

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Check for app store review label
        id: check_app_store_review_label
        if: ${{ contains(steps.pr-labels.outputs.labels, env.APP_STORE_REVIEW_LABEL) }}
        run: |
          echo "App store review label detected"
          echo "app-store-review" >> /tmp/change_tags

      - name: Check for build runtime label
        id: check_build_runtime_label
        if: ${{ contains(steps.pr-labels.outputs.labels, env.BUILD_RUNTIME_LABEL) }}
        run: |
          echo "Build runtime label detected"
          echo "build-runtime" >> /tmp/change_tags

      - name: Check for user facing major label
        id: check_build_runtime_label
        if: ${{ contains(steps.pr-labels.outputs.labels, env.USER_FACING_MAJOR_LABEL) }}
        run: |
          echo "User facing major version label detected"
          echo "user-facing-major" >> /tmp/change_tags

      - name: Check for user facing minor label
        id: check_build_runtime_label
        if: ${{ contains(steps.pr-labels.outputs.labels, env.USER_FACING_MINOR_LABEL) }}
        run: |
          echo "User facing minor version label detected"
          echo "user-facing-minor" >> /tmp/change_tags

      - name: Generate Changelog JSON
        run: |
          jq -s \
            --arg pr_number "${{ env.PR_NUMBER }}" \
            --arg change_title "${{ env.CHANGE_TITLE }}" \
            --arg change_summary "${{ env.CHANGE_SUMMARY }}" \
            --arg change_tags "$(cat /tmp/change_tags)" \
             '{
              "prNumber": $pr_number,
              "changeTitle": $change_title,
              "changeSummary": $change_summary,
              # Split the change tags into an array
              "changeTags": $change_tags | split("\n") | map(select(. != "")),
            }' > .changelog/draft/pr${{ env.PR_NUMBER }}.json

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: ${{ env.CHANGELOG_FILE }}
          default_author: github_actor
          message: "Add changelog for PR #${{ env.PR_NUMBER }}"
